version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: iumar28
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deployfinaldb
    ports:
      - "5432:5432"
    networks:
      - app-network

  jhipster:
    image: iumar28/deployfinal:postgres
    container_name: deployfinal
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/deployfinaldb
      SPRING_DATASOURCE_USERNAME: iumar28
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
